### ISSUE TITLE
How can I run this ?

### ISSUE THREAD

**Issue by applemate** [banker/mongulator#3]
I have zero knowledge about this, just starting out a few day. Could you please put a guide for dummy on how to run this ?

**Comment by banker** [comment]
This probably isn't very useful, since it's just a demo program. But to run you, check it out, and then run

ruby mogulator.rb

If you have the sinatra and mongo gems installed, along with a locally running MongoDB instance, then a web server will start at localhost:4567. You can connect a try MongoDB.
